// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace baithuchanh1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("baithuchanh1.Models.Student", b =>
                {
                    b.Property<string>("IDStudent")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddStudent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameStudent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneStudent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDStudent");

                    b.ToTable("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
